### ISSUE TITLE
重啟專案

### ISSUE THREAD

**Issue by CosmosWeng** [MonsterCavern/jptantan#1]
因為原先的 branch, master 上的 laravel 版本太低有安全性問題
重新開一個新的 branch  叫 main 取代它當主線, 使用 6.x 的 LTS 版本

預想操作如下:
1. 新開一個 branch 叫做 main
2.切換到這個 branch 
3. 把原本資料夾的檔案砍掉
4. 推上 github
4. 重新建立一個 laravel 6.x 版本的專案
5. 把 .git 資料夾移進來
6. 推上 github

### 參考資料
- https://learnku.com/laravel/t/4796/ssh-auth-method-private-key-solution-summary-when-homestead-starts
- https://campus-xoops.tn.edu.tw/modules/tad_book3/html_all.php?tbsn=37
  - 雖然是 5.6 版本, 但基礎是差不多的, 可以學習一下(mvc 和 router 的部分)
- https://www.laravel-dojo.com/workshops/201507-ntpc
  - 這個是我最一開始看的 簡報, 啟蒙先師!

**Comment by jason800417** [comment]
complete

**Comment by CosmosWeng** [comment]
> complete
